<?php
/**
 * @file
 * menu_link.d5a2d69870717510ae152eae169a963cba521868.inc
 */

$api = '2.0.0';

$data = array(
  'expanded' => '0',
  'hidden' => '0',
  'link_path' => '<front>',
  'link_title' => 'Home',
  'menu_name' => 'main-menu',
  'options' => array(),
  'parent_identifier' => NULL,
  'router_path' => '',
  'weight' => '0',
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
