<?php
/**
 * @file
 * variable.delta_blocks_toggle.inc
 */

$api = '2.0.0';

$data = array(
  'content' => array(
    'action-links' => 'action-links',
    'branding' => 'branding',
    'breadcrumb' => 'breadcrumb',
    'feed-icons' => 'feed-icons',
    'logo' => 'logo',
    'messages' => 'messages',
    'page-title' => 'page-title',
    'site-name' => 'site-name',
    'site-slogan' => 'site-slogan',
    'tabs' => 'tabs',
  ),
  'name' => 'delta_blocks_toggle',
);

$dependencies = array();

$optional = array();

$modules = array();
